services:
  pca-study:
    build: .
    image: pca-study-dev:latest
    container_name: pca-study-dev
    restart: unless-stopped
    ports:
      - "0.0.0.0:8082:80"
    cpus: "0.5"
    mem_limit: 256M
    memswap_limit: 256M
    pids_limit: 128
